version: '3.9'
services:
  mongodb:
    image: mongo:7
    container_name: week12-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: week12 
      MONGO_INITDB_USERNAME: week12-admin 
      MONGO_INITDB_PASSWORD: week12-pass
      
    volumes:
      - ./data/db:/data/db 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro